language: node_js
node_js:
   - "4"

os:
   - linux
compiler:
  - gcc

env:
   - CXX=g++-4.8
   - PACKAGE_VERSION="0.0.*"
   - SH=bash
   
addons:
  apt:
    sources:
      ubuntu-toolchain-r-test
    packages:
      - g++-4.8
